[package]
name = "egypt"
version = "0.0.1"
edition = "2021"

[dependencies]
clap = { version = "4.5.2", features = ["derive"] }

[dependencies.rug]
version = "1.24"
default-features = false
features = ["integer", "rational", "std"]

[profile.release]
panic = "abort"
opt-level = 3
debug = false